### ISSUE TITLE
Add feature-gated Arkworks compatibility

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/decaf377#62]

**Comment by hdevalence** [comment]
Blocked by https://github.com/penumbra-zone/decaf377/issues/65

**Comment by TalDerei** [comment]
Unblocked by #66. 

Additionally, implementing the arkworks `PrimeField` trait seems to require satisfying many [trait bounds](https://github.com/arkworks-rs/algebra/blob/4c994ebe1ed5654c40383cd3fc75b8105a8b62dc/ff/src/fields/prime.rs#L28-L34). `PrimeField` further includes `type BigInt: BigInteger` with even more trait bounds. I thought about `type BigInt = BigInt<N>` since an existing [BigInt<N>](https://github.com/arkworks-rs/algebra/blob/4c994ebe1ed5654c40383cd3fc75b8105a8b62dc/ff/src/biginteger/mod.rs#L295) already implements the `BigInteger` trait, but `BigInteger` is a smart wrapper around hard-coded **u64**-bit limbs, which wouldn't work for our context. 

I'm wondering what the optimal approach to implementing the `PrimeField` trait is, and if it's in fact less work than I suspect?

**Comment by hdevalence** [comment]
Yes, there are lots of trait bounds. I think it makes sense to start with just one impl — say Fq, u32 — and see about filling that in. For the BigInt bound we can just use the arkworks type. It's not used for operations that are on the critical path so it doesn't have to be fast. I think it's used for stuff like debug impls.

**Comment by cronokirby** [comment]
This isn't optional yet though, so not closing quite yet.
